[theme]
primaryColor = "#0284c7"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 2000

[browser]
gatherUsageStats = false
